In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('qoute_dataset.csv')

In [5]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [6]:
df.shape

(3038, 2)

In [7]:
quotes = df['quote']
import string
quotes=quotes.str.lower()
quotes=quotes.apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))

In [8]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer


vocab_size = 10000
token = Tokenizer(num_words=vocab_size)
token.fit_on_texts(quotes)

In [20]:
word_index = token.word_index
wprd_index

NameError: name 'wprd_index' is not defined

In [11]:
sequence = token.texts_to_sequences(quotes)

In [12]:
print(sequence[0])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]

In [13]:
X=[]
y=[]

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [14]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Calculate the maximum sequence length
max_sequence_len = max([len(x) for x in X])

# Apply padding to X
X_padded = pad_sequences(X, maxlen=max_sequence_len, padding='pre')

print(f"Padded X shape: {X_padded.shape}")

Padded X shape: (85271, 745)

In [16]:
y = np.array(y)
y.shape

(85271,)

In [17]:
from tensorflow.keras.utils import to_categorical
y_onehot = to_categorical(y, num_classes=vocab_size)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

embedding_dim = 50 # You can adjust this value
rnn_unit = 128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_sequence_len))
model.add(LSTM(rnn_unit)) # Using a GRU or SimpleRNN could also be options
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [19]:
epochs = 100
batch_size = 128

history = model.fit(X_padded, y_onehot, epochs=epochs, batch_size=batch_size, validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 55ms/step - accuracy: 0.0388 - loss: 6.7502 - val_accuracy: 0.0458 - val_loss: 6.6804
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 37s 54ms/step - accuracy: 0.0576 - loss: 6.3186 - val_accuracy: 0.0659 - val_loss: 6.5586
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0808 - loss: 6.0440 - val_accuracy: 0.0896 - val_loss: 6.4622
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0988 - loss: 5.8258 - val_accuracy: 0.0970 - val_loss: 6.4145
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1099 - loss: 5.6392 - val_accuracy: 0.1024 - val_loss: 6.4060
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1197 - loss: 5.4656 - val_accuracy: 0.1082 - val_loss: 6.4120
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1282 - loss: 5.3064 - val_accuracy: 0.1078 - val_loss: 6.4445
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1370 - loss: 5.1602 - val_accuracy: 0.1099 - val_loss: 6.4727
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1435 - loss: 5.0220 - val_accuracy: 0.1108 - val_loss: 6.5219
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1509 - loss: 4.8898 - val_accuracy: 0.1127 - val_loss: 6.5773
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1574 - loss: 4.7614 - val_accuracy: 0.1130 - val_loss: 6.6268
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1655 - loss: 4.6337 - val_accuracy: 0.1155 - val_loss: 6.6889
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1742 - loss: 4.5104 - val_accuracy: 0.1110 - val_loss: 6.7401
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1846 - loss: 4.3874 - val_accuracy: 0.1130 - val_loss: 6.8104
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1966 - loss: 4.2676 - val_accuracy: 0.1106 - val_loss: 6.8905
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2090 - loss: 4.1510 - val_accuracy: 0.1116 - val_loss: 6.9491
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2229 - loss: 4.0396 - val_accuracy: 0.1098 - val_loss: 7.0256
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2362 - loss: 3.9325 - val_accuracy: 0.1100 - val_loss: 7.0973
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.2523 - loss: 3.8300 - val_accuracy: 0.1086 - val_loss: 7.1767
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2646 - loss: 3.7344 - val_accuracy: 0.1088 - val_loss: 7.2386
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.2789 - loss: 3.6447 - val_accuracy: 0.1091 - val_loss: 7.3397
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2920 - loss: 3.5593 - val_accuracy: 0.1082 - val_loss: 7.4114
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3051 - loss: 3.4794 - val_accuracy: 0.1060 - val_loss: 7.4724
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3160 - loss: 3.4041 - val_accuracy: 0.1072 - val_loss: 7.5599
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3283 - loss: 3.3320 - val_accuracy: 0.1042 - val_loss: 7.6179
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3386 - loss: 3.2628 - val_accuracy: 0.1028 - val_loss: 7.6948
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3501 - loss: 3.1965 - val_accuracy: 0.1026 - val_loss: 7.7638
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3603 - loss: 3.1326 - val_accuracy: 0.1033 - val_loss: 7.8403
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3702 - loss: 3.0717 - val_accuracy: 0.1007 - val_loss: 7.9073
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3804 - loss: 3.0114 - val_accuracy: 0.0983 - val_loss: 7.9715
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3891 - loss: 2.9555 - val_accuracy: 0.0986 - val_loss: 8.0368
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4001 - loss: 2.9000 - val_accuracy: 0.0970 - val_loss: 8.1105
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.4078 - loss: 2.8478 - val_accuracy: 0.0984 - val_loss: 8.1724
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4187 - loss: 2.7958 - val_accuracy: 0.0970 - val_loss: 8.2243
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4264 - loss: 2.7448 - val_accuracy: 0.0967 - val_loss: 8.3148
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4354 - loss: 2.6962 - val_accuracy: 0.0957 - val_loss: 8.3611
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4439 - loss: 2.6488 - val_accuracy: 0.0940 - val_loss: 8.4350
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4529 - loss: 2.6036 - val_accuracy: 0.0939 - val_loss: 8.4853
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4602 - loss: 2.5582 - val_accuracy: 0.0920 - val_loss: 8.5632
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4697 - loss: 2.5144 - val_accuracy: 0.0911 - val_loss: 8.6162
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4769 - loss: 2.4729 - val_accuracy: 0.0916 - val_loss: 8.6839
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4836 - loss: 2.4324 - val_accuracy: 0.0905 - val_loss: 8.7304
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4918 - loss: 2.3926 - val_accuracy: 0.0891 - val_loss: 8.8194
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4981 - loss: 2.3548 - val_accuracy: 0.0937 - val_loss: 8.8556
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5043 - loss: 2.3150 - val_accuracy: 0.0899 - val_loss: 8.9281
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5122 - loss: 2.2788 - val_accuracy: 0.0870 - val_loss: 8.9792
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5178 - loss: 2.2426 - val_accuracy: 0.0877 - val_loss: 9.0346
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.5259 - loss: 2.2067 - val_accuracy: 0.0888 - val_loss: 9.0988
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5322 - loss: 2.1726 - val_accuracy: 0.0856 - val_loss: 9.1624
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5394 - loss: 2.1396 - val_accuracy: 0.0871 - val_loss: 9.2279
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5452 - loss: 2.1075 - val_accuracy: 0.0876 - val_loss: 9.2821
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5528 - loss: 2.0761 - val_accuracy: 0.0867 - val_loss: 9.3422
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5584 - loss: 2.0455 - val_accuracy: 0.0860 - val_loss: 9.4025
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5649 - loss: 2.0138 - val_accuracy: 0.0865 - val_loss: 9.4480
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5701 - loss: 1.9843 - val_accuracy: 0.0849 - val_loss: 9.4939
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5767 - loss: 1.9555 - val_accuracy: 0.0841 - val_loss: 9.5590
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5812 - loss: 1.9281 - val_accuracy: 0.0831 - val_loss: 9.6199
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5875 - loss: 1.9010 - val_accuracy: 0.0834 - val_loss: 9.6471
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5934 - loss: 1.8721 - val_accuracy: 0.0813 - val_loss: 9.7123
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5978 - loss: 1.8472 - val_accuracy: 0.0848 - val_loss: 9.7670
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6033 - loss: 1.8209 - val_accuracy: 0.0822 - val_loss: 9.8453
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6078 - loss: 1.7970 - val_accuracy: 0.0826 - val_loss: 9.8792
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6140 - loss: 1.7719 - val_accuracy: 0.0821 - val_loss: 9.9428
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6175 - loss: 1.7466 - val_accuracy: 0.0814 - val_loss: 10.0175
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6231 - loss: 1.7237 - val_accuracy: 0.0824 - val_loss: 10.0334
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 57ms/step - accuracy: 0.6276 - loss: 1.7003 - val_accuracy: 0.0813 - val_loss: 10.0961
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6314 - loss: 1.6778 - val_accuracy: 0.0806 - val_loss: 10.1588
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6355 - loss: 1.6565 - val_accuracy: 0.0813 - val_loss: 10.2054
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6408 - loss: 1.6356 - val_accuracy: 0.0815 - val_loss: 10.2703
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6458 - loss: 1.6135 - val_accuracy: 0.0804 - val_loss: 10.3206
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6499 - loss: 1.5938 - val_accuracy: 0.0788 - val_loss: 10.3739
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6547 - loss: 1.5723 - val_accuracy: 0.0816 - val_loss: 10.4268
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6587 - loss: 1.5538 - val_accuracy: 0.0809 - val_loss: 10.4742
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6617 - loss: 1.5417 - val_accuracy: 0.0788 - val_loss: 10.5404
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6660 - loss: 1.5157 - val_accuracy: 0.0802 - val_loss: 10.5756
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6692 - loss: 1.4958 - val_accuracy: 0.0790 - val_loss: 10.6035
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6741 - loss: 1.4795 - val_accuracy: 0.0804 - val_loss: 10.6755
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6770 - loss: 1.4630 - val_accuracy: 0.0799 - val_loss: 10.7368
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6813 - loss: 1.4435 - val_accuracy: 0.0780 - val_loss: 10.7854
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6865 - loss: 1.4261 - val_accuracy: 0.0790 - val_loss: 10.8252
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6888 - loss: 1.4106 - val_accuracy: 0.0775 - val_loss: 10.8822
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6938 - loss: 1.3929 - val_accuracy: 0.0760 - val_loss: 10.9421
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6957 - loss: 1.3776 - val_accuracy: 0.0772 - val_loss: 10.9750
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6996 - loss: 1.3608 - val_accuracy: 0.0783 - val_loss: 11.0272
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7020 - loss: 1.3460 - val_accuracy: 0.0773 - val_loss: 11.0723
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7072 - loss: 1.3303 - val_accuracy: 0.0783 - val_loss: 11.1092
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7096 - loss: 1.3155 - val_accuracy: 0.0797 - val_loss: 11.1791
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7122 - loss: 1.3026 - val_accuracy: 0.0769 - val_loss: 11.2272
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.7153 - loss: 1.2863 - val_accuracy: 0.0758 - val_loss: 11.2820
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7201 - loss: 1.2723 - val_accuracy: 0.0770 - val_loss: 11.3282
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7215 - loss: 1.2592 - val_accuracy: 0.0754 - val_loss: 11.3728
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7254 - loss: 1.2437 - val_accuracy: 0.0767 - val_loss: 11.4144
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7278 - loss: 1.2308 - val_accuracy: 0.0768 - val_loss: 11.4766
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7309 - loss: 1.2195 - val_accuracy: 0.0761 - val_loss: 11.5247
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7342 - loss: 1.2060 - val_accuracy: 0.0748 - val_loss: 11.5485
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7371 - loss: 1.1945 - val_accuracy: 0.0739 - val_loss: 11.6028
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7390 - loss: 1.1826 - val_accuracy: 0.0750 - val_loss: 11.6542
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7415 - loss: 1.1691 - val_accuracy: 0.0769 - val_loss: 11.6983
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7461 - loss: 1.1560 - val_accuracy: 0.0776 - val_loss: 11.7291
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7474 - loss: 1.1439 - val_accuracy: 0.0735 - val_loss: 11.7948

In [21]:
model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [25]:
# Create a reverse word index for mapping integer to word
reverse_word_index = dict([(value, key) for (key, value) in token.word_index.items()])

def predict_next_word(seed_text, model, tokenizer, max_sequence_len, reverse_word_index):
    # Preprocess the seed text
    seed_text = seed_text.lower()
    seed_text = seed_text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize the seed text
    sequence = tokenizer.texts_to_sequences([seed_text])[0]

    # Pad the sequence to the maximum length
    padded_sequence = pad_sequences([sequence], maxlen=max_sequence_len, padding='pre')

    # Predict the next word's probabilities
    predicted_probabilities = model.predict(padded_sequence, verbose=0)[0]

    # Get the index of the most probable word
    predicted_word_index = np.argmax(predicted_probabilities)

    # Map the index back to a word
    predicted_word = reverse_word_index.get(predicted_word_index, "")

    return predicted_word

In [34]:
def predict_sentence(seed_text, model, tokenizer, max_sequence_len, reverse_word_index, num_words=10):
  for _ in range(num_words):
    next_word = predict_next_word(seed_text, model, tokenizer, max_sequence_len, reverse_word_index)
    if next_word == '':
      break
    seed_text += ' ' + next_word
  return seed_text

In [36]:
# Example usage:
seed_text = "who is the"
complete_text = predict_sentence(seed_text, model, token, max_sequence_len, reverse_word_index)
print(f"Seed Text: '{seed_text}'")
print(f"Predicted Next Word: '{complete_text}'")

Seed Text: 'who is the'
Predicted Next Word: 'who is the unknown she will rise from a man who is constantly'

In [37]:
import pickle

# Save the tokenizer
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(token, f)

# Save max_sequence_len
with open('max_sequence_len.pkl', 'wb') as f:
    pickle.dump(max_sequence_len, f)

print("Tokenizer and max_sequence_len saved successfully.")

Tokenizer and max_sequence_len saved successfully.